urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import MainView as ProjectMainView
from .views import InformationView as ProjectInformationView
from .views import InformationCreateView as ProjectInformationCreateView
from .views import InformationUpdateView as ProjectInformationUpdateView
from .views import InformationDeleteView as ProjectInformationDeleteView
from .views import InformationDirectorsUpdateView as ProjectInformationDirectorsUpdateView
from .views import FeedbackListView as ProjectFeedbackListView

# Create your urls here.
urlpatterns = [
    path('', login_required(ProjectMainView.as_view()), name='projects-main'),
    path('new/', login_required(ProjectInformationCreateView.as_view()),
         name='project-create'),
    path('<pk>/update/', login_required(ProjectInformationUpdateView.as_view()),
         name='project-update'),
    path('<pk>/delete/', login_required(ProjectInformationDeleteView.as_view()),
         name='project-delete'),
    path('<pk>/directors/', login_required(ProjectInformationDirectorsUpdateView.as_view()),
         name='project-directors'),
    path('<pk>/detail/', login_required(ProjectInformationView.as_view()),
         name='project-information'),
    path('<pk>/feedbacks/', login_required(ProjectFeedbackListView.as_view()),
         name='project-feedbacks'),
]

models.py
import string

from django.shortcuts import reverse
from django.core.validators import FileExtensionValidator
from django.db import models
from django.utils import timezone
from random import choice

# Create your models here.

def custom_path(instance, filename):
    arr = [choice(string.ascii_letters) for _ in range(8)]
    pid = ''.join(arr)
    extension = filename.split('.')[-1]
    date = timezone.now()
    return 'file/%s/%s/%s/%s.%s' % (
        date.year,
        date.month,
        date.day,
        pid,
        extension,
    )

class Information(models.Model):
    secure_levels = (
        (1, '모두 참여 가능'),
        (2, '팀원 지정'),
        (3, '개인 진행'),
    )
    name = models.CharField(
        max_length=30,
        verbose_name='프로젝트 이름',
        unique=True,
    )
    project_manager = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE,
        related_name='project_manager',
        verbose_name='총괄 디렉터',
    )
    directors = models.ManyToManyField(
        'auth.User',
        blank=True,
        related_name='project_directors',
        verbose_name='팀원',
    )
    description = models.TextField(
        blank=True,
        verbose_name='프로젝트 소개',
    )
    purpose = models.TextField(
        max_length=150,
        blank=True,
        verbose_name='목적',
    )
    reason = models.TextField(
        max_length=150,
        blank=True,
        verbose_name='주제 선정 이유',
    )
    plan = models.TextField(
        blank=True,
        verbose_name='진행 계획',
    )
    secure_level = models.PositiveIntegerField(
        choices=secure_levels,
        verbose_name='참여 가능 범위',
    )
    file = models.FileField(upload_to=custom_path, validators=[FileExtensionValidator(allowed_extensions=['pdf'])], blank=True, verbose_name='기획서')
    published_date = models.DateField(editable=False)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.published_date = timezone.now()
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('project-information', kwargs={'pk': self.pk})


class Feedback(models.Model):
    creation_time = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=256)
    content = models.TextField()
    project = models.ForeignKey(Information, on_delete=models.CASCADE)

views.py
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.db.models import Q
from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView
from .models import Information as ProjectInformation
from .models import Feedback as ProjectFeedback

# Create your views here.


class MainView(ListView):
    template_name = 'projects/pages/main.html'
    model = ProjectInformation
    context_object_name = 'projects'

    def get_queryset(self):
        user = self.request.user
        return ProjectInformation.objects.filter(
            Q(secure_level=1) |
            Q(directors__exact=user, secure_level=2) |
            Q(project_manager=user)
        ).distinct()


class InformationView(DetailView):
    template_name = 'projects/pages/information.html'
    model = ProjectInformation
    context_object_name = 'project'


class InformationCreateView(CreateView):
    template_name = 'projects/forms/information.html'
    model = ProjectInformation
    fields = ('name', 'description', 'purpose', 'reason', 'plan', 'secure_level', 'file')

    def form_valid(self, form):
        form.instance.project_manager = self.request.user
        return super(InformationCreateView, self).form_valid(form)


class InformationUpdateView(UpdateView):
    template_name = 'projects/forms/information.html'
    model = ProjectInformation
    fields = ('name', 'description', 'purpose', 'reason', 'plan', 'secure_level', 'file')


class InformationDirectorsUpdateView(UpdateView):
    template_name = 'projects/forms/information_directors.html'
    model = ProjectInformation
    fields = ('directors',)

    def form_valid(self, form):
        pass


class InformationDeleteView(DeleteView):
    template_name = 'projects/forms/information_delete.html'
    model = ProjectInformation
    context_object_name = 'project'
    success_url = reverse_lazy('projects-main')


class FeedbackListView(DetailView):
    template_name = 'projects/pages/feedbacks.html'
    model = ProjectInformation
    context_object_name = 'project'

    def get_context_data(self, **kwargs):
        context = super(FeedbackListView, self).get_context_data(**kwargs)
        feedbacks = ProjectFeedback.objects.filter(project=self.get_object())
        context['feedbacks'] = feedbacks
        return context

templates/projects/forms/information.html
{% extends 'projects/pages/main.html' %}

{% block item-content %}
<form method="POST">
    {% csrf_token %}
    <div class="main-row p-0 m-0">
        <h3>새 프로젝트 등록</h3>
        <input class="btn btn-outline-secondary main-button-style ml-auto" type="submit" value="&check; 등록하기" />
        <a class="btn btn-outline-secondary main-button-style ml-3 mr-0" href="{% url 'projects-main' %}" role="button">&#10005; 취소하기</a>
    </div>
    <hr></hr>
    <div class="container main-row p-0 m-0">
        <div class="form-group col-6">
            <label class="text-bold" for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
            <input class="form-control" type="text" id="{{ form.name.id_for_label }}" name="{{ form.name.html_name }}" maxlength="30" placeholder="{{ form.name.label }}" value="{% if form.name.value %}{{ form.name.value }}{% endif %}" required />
        </div>
        <div class="form-group col-12">
            <label class="text-bold" for="{{ form.description.id_for_label }}">{{ form.description.label }}</label>
            <textarea class="form-control" id="{{ form.description.id_for_label }}" name="{{ form.description.html_name }}" rows="10" placeholder="{{ form.description.label }}">{% if form.description.value %}{{ form.description.value }}{% endif %}</textarea>
        </div>
        <div class="form-group col-12">
            <label class="text-bold" for="{{ form.purpose.id_for_label }}">{{ form.purpose.label }} (150자 내외)</label>
            <p>이번 프로젝트를 통해서 습득하고자 하는 기술, 또는 공부하고자 하는 학술 분야에 관해서 간단하게 적어주세요.</p>
            <textarea class="form-control" id="{{ form.purpose.id_for_label }}" name="{{ form.purpose.html_name }}" rows="10" placeholder="{{ form.purpose.label }}">{% if form.purpose.value %}{{ form.purpose.value }}{% endif %}</textarea>
        </div>
        <div class="form-group col-12">
            <label class="text-bold" for="{{ form.reason.id_for_label }}">{{ form.reason.label }} (150자 내외)</label>
            <p>위의 목적을 달성하는데 있어 프로젝트 주제를 이와 같이 선정하게 된 이유 혹은 과정을 간단하게 적어주세요.</p>
            <textarea class="form-control" id="{{ form.reason.id_for_label }}" name="{{ form.reason.html_name }}" rows="10" placeholder="{{ form.reason.label }}">{% if form.reason.value %}{{ form.reason.value }}{% endif %}</textarea>
        </div>
        <div class="form-group col-12">
            <label class="text-bold" for="{{ form.plan.id_for_label }}">{{ form.plan.label }}</label>
            <p>현재까지 진행 상황과 함께 앞으로 계획을 구체적으로 적어주세요. 기존 계획이 지켜지지 않았을 경우, 팀원과 상의하여 보완 작업을 거친 후에 기재해주시기 바랍니다.</p>
            <textarea class="form-control" id="{{ form.plan.id_for_label }}" name="{{ form.plan.html_name }}" rows="10" placeholder="{{ form.plan.label }}">{% if form.plan.value %}{{ form.plan.value }}{% endif %}</textarea>
        </div>
        <div class="form-group col-12 col-md-4">
            <label class="text-bold" for="{{ form.secure_level.id_for_label }}">{{ form.secure_level.label }}</label>
            <p>'팀원 지정'으로 설정하시고, 프로젝트 등록 후에 '멤버 편집'메뉴로 들어가서 멤버를 추가해주세요.</p>
            <select class="form-control" id="{{ form.secure_level.id_for_label }}" name="{{ form.secure_level.html_name }}" required>
                {% for opt in form.secure_level %}
                {{ opt }}
                {% endfor %}
            </select>
        </div>
        <div class="form-group col-lg-8 col-12">
            <label class="text-bold" for="{{ form.file.id_for_label }}">{{ form.file.label }}</label>
            <div>{{ form.file }}</div>
        </div>
    </div>
</form>
{% endblock %}

templates/projects/forms/information_delete.html
{% extends 'projects/pages/main.html' %}

{% block item-content %}
<form method="POST">
    {% csrf_token %}
    <p>{{ project.name }} 프로젝트를 삭제하시겠습니까?</p>
    <input class="btn btn-outline-secondary main-button-style" type="submit" value="삭제" />
    <a class="btn btn-outline-secondary main-button-style" role="button" href="{% url 'project-information' pk=project.pk %}">취소</a>
</form>
{% endblock %}

templates/projects/forms/information_directors.html
{% extends 'projects/pages/main.html' %}

{% block item-content %}
<form method="POST">
    {% csrf_token %}
    <div class="main-row p-0 m-0">
        <h3>프로젝트 멤버 편집</h3>
        <input class="btn btn-outline-secondary main-button-style ml-auto" type="submit" value="&check; 등록하기" />
        <a class="btn btn-outline-secondary main-button-style ml-3 mr-0" href="{% url 'projects-main' %}" role="button">&#10005; 취소하기</a>
    </div>
    <hr></hr>
    <div class="container main-row p-0 m-0">
        <div class="form-group col-6">
            <label for="{{ form.directors.id_for_label }}">{{ form.directors.label }}</label>
            <select class="form-control" name="{{ form.directors.html_name }}" id="{{ form.directors.id_for_label }}" multiple="multiple">
                {% for opt in form.directors %}
                {{ opt }}
                {% endfor %}
            </select>
            <p class="text-muted py-1">* 다중 선택은 Window는 Ctrl키, 맥은 Command키를 눌러서 선택해주세요.</p>
        </div>
    </div>
</form>
{% endblock %}

templates/projects/pages/feedbacks.html
{% extends 'projects/pages/information.html' %}

{% block detail-feedback-style %}
active
{% endblock %}

{% block detail-content %}
<div class="py-3">
    {% if feedbacks %}
        <ul class="main-list">
        {% for feedback in feedbacks %}
        <li class="main-list-item">
            <div class="main-list-item-info">
                <span class="text-bold">{{ feedback.name }}</span>
                <span>{{ feedback.creation_time }}</span>
                <h3 class="py-3">{{ feedback.content }}</h3>
            </div>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <div>아직 등록된 피드백이 없습니다.</div>
    {% endif %}
</div>
{% endblock %}

templates/projects/pages/information.html
{% extends 'projects/pages/main.html' %}

{% block item-content %}
<div class="main-row p-0 m-0">
    <h3>Project : {{ project.name }}</h3>
    <div class="btn-group ml-auto" role="group" aria-label="Project Detail Tab">
        <a class="btn btn-outline-secondary main-button-style {% block detail-feedback-style %}{% endblock %}" href="{% url 'project-feedbacks' pk=project.pk %}">피드백</a>
        {% if user == project.project_manager %}
        <a class="btn btn-outline-secondary main-button-style" href="{% url 'project-update' pk=project.pk %}">수정</a>
        <a class="btn btn-outline-secondary main-button-style" href="{% url 'project-delete' pk=project.pk %}">삭제</a>
        <a class="btn btn-outline-secondary main-button-style" href="{% url 'project-directors' pk=project.pk %}">멤버 편집</a>
        {% endif %}
    </div>
        <a class="btn btn-outline-secondary main-button-style ml-auto" href="{% url 'projects-main' %}">&#10149; 리스트로 돌아가기</a>
</div>
<hr></hr>
{% block detail-content %}
<div class="py-3">
    <h5 class="text-bold">총괄 디렉터</h5>
    <p>{{ project.project_manager.first_name }}({{ project.project_manager.username }})</p>
</div>
<div class="py-3">
    <h5 class="text-bold">등록일시</h5>
    <p>{{ project.published_date }}</p>
</div>
<div class="py-3">
    <h5 class="text-bold">프로젝트 참여 가능 범위</h5>
    <p>{{ project.get_secure_level_display }}</p>
</div>
<div class="py-3">
    <h5 class="text-bold">프로젝트 멤버</h5>
    {% if project.directors.all %}
    {% for director in project.directors.all %}
    <span>{{ director.first_name }}({{ director.username }})</span>
    {% endfor %}
    {% else %}
    <span>등록된 프로젝트 멤버가 없습니다.</span>
    {% endif %}
</div>
<div class="py-3">
    <h5 class="text-bold">프로젝트 소개</h5>
    {% if project.description %}
    <p>{{ project.description }}</p>
    {% else %}
    <p>프로젝트에 대한 설명이 없습니다.</p>
    {% endif %}
</div>
<div class="py-3">
    <h5 class="text-bold">프로젝트 목적</h5>
    {% if project.purpose %}
    <p>{{ project.purpose }}</p>
    {% else %}
    <p>프로젝트 목적에 대한 설명이 없습니다.</p>
    {% endif %}
</div>
<div class="py-3">
    <h5 class="text-bold">주제 선정 이유</h5>
    {% if project.reason %}
    <p>{{ project.reason }}</p>
    {% else %}
    <p>주제 선정 이유에 대한 설명이 없습니다.</p>
    {% endif %}
</div>
<div class="py-3">
    <h5 class="text-bold">진행 계획</h5>
    {% if project.plan %}
    <p>{{ project.plan }}</p>
    {% else %}
    <p>프로젝트 진행 계획에 대한 설명이 없습니다.</p>
    {% endif %}
</div>
<div class="py-3">
    <h5 class="text-bold">프로젝트 기획서</h5>
    {% if project.file %}
    <a href="{{ project.file.url }}">{{ project.file.url }}</a>
    {% else %}
    <div>기획서를 등록해주세요</div>
    {% endif %}
</div>
{% endblock %}
{% endblock %}

templates/projects/pages/main.html
{% extends 'dashboard/base.html' %}

{% block projects-style-class %}
current-menu
{% endblock %}

{% block item-content %}
<div class="main-row p-0 m-0">
    <h3>Projects</h3>
    <a class="btn btn-outline-secondary main-button-style ml-auto" href="{% url 'project-create' %}">&plus; 새 프로젝트</a>
</div>
<hr></hr>
{% if projects|length > 0 %}
<ul class="main-list">
    {% for project in projects %}
    <li class="main-list-item">
        <div class="main-row p-0 m-0">
            <div class="col-lg-10 col-md-9 main-list-item-info">
                <h5 class="pb-0 mb-0">{{ project.name }}</h5>
                <p>{{ project.published_date }}</p>
            </div>
            <div class="col-lg-2 col-md-3 main-list-item-info">
                <a class="btn btn-outline-secondary main-button-style w-100 my-1" href="{% url 'project-information' pk=project.pk %}">&ii; Information</a>
                <a class="btn btn-outline-secondary main-button-style w-100 my-1" href="#">&#10025; Join</a>
                <a class="btn btn-outline-secondary main-button-style w-100 my-1" href="{% url 'project-feedbacks' pk=project.pk %}">&#10063; Feedback</a>
            </div>
        </div>
    </li>
    {% endfor %}
</ul>
{% else %}
<div>현재 진행 중인 프로젝트가 없습니다.</div>
{% endif %}
{% endblock %}